# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - project-azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  # Étape 1 : Installer Make (nécessaire pour utiliser le Makefile)
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make
 
      # Étape 2 : Initialiser l'environnement virtuel
      - name: Initialize virtual environment
        run: make init # Exécute la commande "make init" pour créer .venv
 
      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: make install # Exécute la commande "make install" pour installer les dépendances
 
      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: make test # Exécute la commande "make test" pour lancer les tests
 
      # Étape 5 : Construire l'image Docker
      - name: Build Docker image
        run: make build # Exécute la commande "make build" pour créer une image Docker
 
      # Étape 6 : supprimer les fichiers non necessaires
      - name: Clean cache files
        run: make clean
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ED4AD282998F4283814B1968A8988CEB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B8A981DF2BD74928B8F551727746B060 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BB61F611461042FB81F36AC6E7372B3F }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'project-azure'
          slot-name: 'Production'
          